package com.redhat.poc.mytm_brms;

import java.util.ArrayList;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(3d6acd2f6b941384d040b62df6c1d102)
 */
@org.kie.api.definition.type.Label(value = "Bundle")
public class Bundle  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Bundle ID")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String bundleId;
    
    @org.kie.api.definition.type.Label(value = "Products")
    @org.kie.api.definition.type.Position(value = 1)
    private java.util.List<com.redhat.poc.mytm_brms.Product> products;

    public Bundle() {
    }

    public Bundle(java.lang.String bundleId, java.util.List<com.redhat.poc.mytm_brms.Product> products) {
        this.bundleId = bundleId;
        this.products = products;
    }


    
    public java.lang.String getBundleId() {
        return this.bundleId;
    }

    public void setBundleId(java.lang.String bundleId) {
        this.bundleId = bundleId;
    }
    
    public java.util.List<com.redhat.poc.mytm_brms.Product> getProducts() {
        if (this.products == null) this.products = new ArrayList<Product>();
	return this.products;
    }

    public void setProducts(java.util.List<com.redhat.poc.mytm_brms.Product> products) {
        this.products = products;
    }
}
