package com.redhat.poc.mytm_brms;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(245bb473f1688530722a3fd6a26cf28f)
 */
@org.kie.api.definition.type.Label(value = "Product")
public class Product  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Part Number")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String partNumber;
    
    @org.kie.api.definition.type.Label(value = "Product Name")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String productName;

    public Product() {
    }

    public Product(java.lang.String partNumber, java.lang.String productName) {
        this.partNumber = partNumber;
        this.productName = productName;
    }


    
    public java.lang.String getPartNumber() {
        return this.partNumber;
    }

    public void setPartNumber(java.lang.String partNumber) {
        this.partNumber = partNumber;
    }
    
    public java.lang.String getProductName() {
        return this.productName;
    }

    public void setProductName(java.lang.String productName) {
        this.productName = productName;
    }
}